### ISSUE TITLE
Forgot how to publish with sbt-bintray

### ISSUE THREAD

**Issue by JohnReedLOL** [sbt/sbt-bintray#164]
I had previously published this library: https://github.com/JohnReedLOL/pos#Getting-Started 

Using sbt-bintray: https://bintray.com/johnreed2/maven/pos

To sign in, I know my email, username, and password: https://i.imgur.com/2wo5qH7.png 

I haven't published in a long time, but when I try to publish, I an error that tells me to set BINTRAY_USER and BINTRAY_PASS environment variables, so I set them like this:

```
JohnMichaelsAir:pos john-michaelreed$ export BINTRAY_USER=johnreed2
JohnMichaelsAir:pos john-michaelreed$ export BINTRAY_PASS=**************
```

This is the same username and password that I use to sign into here: https://i.imgur.com/WSkaov4.png

When I try to publish with "BINTRAY_USER" and "BINTRAY_PASS" set I get this:

```
sbt:pos> + publish
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Reapplying settings...
[info] Set current project to pos (in build file:/Users/john-michaelreed/IdeaProjects/pos/)
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0-sources.jar ...
[info] Done packaging.
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0.jar ...
[info] Main Scala API documentation to /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/api...
[info] Wrote /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0.pom
[info] Done packaging.
model contains 19 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0-javadoc.jar ...
[info] Done packaging.
[error] java.lang.RuntimeException: error uploading to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.11/2.2.0/pos_2.11-2.2.0.pom: {"message":"This resource requires authentication"}
[error]         at bintray.BintrayMavenRepository.put(Resolver.scala:54)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:497)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:496)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:496)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2416)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2416)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (publish) error uploading to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.11/2.2.0/pos_2.11-2.2.0.pom: {"message":"This resource requires authentication"}
[error] Total time: 12 s, completed Feb 2, 2019, 8:51:52 PM
sbt:pos> 
```

What do I do?

**Comment by JohnReedLOL** [comment]
Oh wait, I think I figured it out. When you say "BINTRAY_PASS", you really mean "BINTRAY_API_KEY".

API_Key: https://i.imgur.com/RgQCrpm.png 

```
sbt:pos> + publish
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Reapplying settings...
[info] Set current project to pos (in build file:/Users/john-michaelreed/IdeaProjects/pos/)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/Users/john-michaelreed/.ivy2/cache/io.netty/netty/bundles/netty-3.10.0.Final.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Wrote /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0.pom
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0.jar ...
[info] Main Scala API documentation to /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/api...
[info] Done packaging.
model contains 19 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.11/pos_2.11-2.2.0-javadoc.jar ...
[info] Done packaging.
[info]  published pos_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.11/2.2.0/pos_2.11-2.2.0.pom
[info]  published pos_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.11/2.2.0/pos_2.11-2.2.0.jar
[info]  published pos_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.11/2.2.0/pos_2.11-2.2.0-sources.jar
[info]  published pos_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.11/2.2.0/pos_2.11-2.2.0-javadoc.jar
[info] johnreed2/pos@2.2.0 was released
[success] Total time: 21 s, completed Feb 2, 2019, 9:04:37 PM
[info] Setting Scala version to 2.13.0-M5 on 1 projects.
[info] Reapplying settings...
[info] Set current project to pos (in build file:/Users/john-michaelreed/IdeaProjects/pos/)
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.13.0-M5/pos_2.13.0-M5-2.2.0-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.13.0-M5/pos_2.13.0-M5-2.2.0.pom
[info] Main Scala API documentation to /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.13.0-M5/api...
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.13.0-M5/pos_2.13.0-M5-2.2.0.jar ...
[info] Done packaging.
[warn] /Users/john-michaelreed/IdeaProjects/pos/src/main/scala/com/github/johnreedlol/internal/Helpers.scala:39:29: Unused import
[warn]       import scala.language.existentials
[warn]                             ^
[warn] /Users/john-michaelreed/IdeaProjects/pos/src/main/scala/com/github/johnreedlol/package.scala:19:36: Unused import
[warn] import scala.language.experimental.macros
[warn]                                    ^
[warn] /Users/john-michaelreed/IdeaProjects/pos/src/main/scala/com/github/johnreedlol/package.scala:104:25: Unused import
[warn]   import scala.language.existentials // MacroHelperMethod uses the existential type feature
[warn]                         ^
model contains 19 documentable templates
[warn] three warnings found
[info] Main Scala API documentation successful.
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.13.0-M5/pos_2.13.0-M5-2.2.0-javadoc.jar ...
[info] Done packaging.
[info]  published pos_2.13.0-M5 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.13.0-M5/2.2.0/pos_2.13.0-M5-2.2.0.pom
[info]  published pos_2.13.0-M5 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.13.0-M5/2.2.0/pos_2.13.0-M5-2.2.0.jar
[info]  published pos_2.13.0-M5 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.13.0-M5/2.2.0/pos_2.13.0-M5-2.2.0-sources.jar
[info]  published pos_2.13.0-M5 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.13.0-M5/2.2.0/pos_2.13.0-M5-2.2.0-javadoc.jar
[info] johnreed2/pos@2.2.0 was released
[success] Total time: 20 s, completed Feb 2, 2019, 9:04:57 PM
[info] Setting Scala version to 2.12.8 on 1 projects.
[info] Reapplying settings...
[info] Set current project to pos (in build file:/Users/john-michaelreed/IdeaProjects/pos/)
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.12/pos_2.12-2.2.0-sources.jar ...
[info] Done packaging.
[info] Wrote /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.12/pos_2.12-2.2.0.pom
[info] Main Scala API documentation to /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.12/api...
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.12/pos_2.12-2.2.0.jar ...
[info] Done packaging.
model contains 19 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/john-michaelreed/IdeaProjects/pos/target/scala-2.12/pos_2.12-2.2.0-javadoc.jar ...
[info] Done packaging.
[info]  published pos_2.12 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.12/2.2.0/pos_2.12-2.2.0.pom
[info]  published pos_2.12 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.12/2.2.0/pos_2.12-2.2.0.jar
[info]  published pos_2.12 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.12/2.2.0/pos_2.12-2.2.0-sources.jar
[info]  published pos_2.12 to https://api.bintray.com/maven/johnreed2/maven/maven/com/github/johnreedlol/pos_2.12/2.2.0/pos_2.12-2.2.0-javadoc.jar
[info] johnreed2/pos@2.2.0 was released
[success] Total time: 23 s, completed Feb 2, 2019, 9:05:20 PM
[info] Reapplying settings...
[info] Set current project to pos (in build file:/Users/john-michaelreed/IdeaProjects/pos/)
sbt:pos> exit
[info] shutting down server

```
