### ISSUE TITLE
unpublish fails when trying to remove artifact that should be skipped

### ISSUE THREAD

**Issue by seglo** [sbt/sbt-bintray#167]
I have a multi-project SBT build where the root project has `skip in publish := true`, but when I attempt to unpublish the entire project with `bintrayUnpublish` I receive an error when it attempts to unpublish the root project.

```
[error] java.lang.RuntimeException: failed to discard lightbend/root@1.0.1-SNAPSHOT: {"message":"Version '1.0.1-SNAPSHOT' was not found"}
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at bintray.BintrayRepo.unpublish(BintrayRepo.scala:84)
[error]         at bintray.BintrayPlugin$.$anonfun$bintrayPublishSettings$19(BintrayPlugin.scala:108)
[error]         at bintray.BintrayPlugin$.$anonfun$bintrayPublishSettings$19$adapted(BintrayPlugin.scala:106)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (bintrayUnpublish) failed to discard lightbend/root@1.0.1-SNAPSHOT: {"message":"Version '1.0.1-SNAPSHOT' was not found"}
```

**Comment by dwijnand** [comment]
Fixed in #168.
