### ISSUE TITLE
405 Method Not Allowed on bintray::publish

### ISSUE THREAD

**Issue by arschles** [sbt/sbt-bintray#37]
I am trying to migrate the [Cascade Project](https://github.com/paypal/cascade) to use Bintray, since I've had a lot of problems with Sonatype OSS lately. I ran `bintray::publish` after running `bintray::changeCredentials` successfully. All of my tests ran and scaladoc generated correctly, and when the was done, I got the following errors:

``` bash
[trace] Stack trace suppressed: run last cascade-json/*:publish for the full output.
[trace] Stack trace suppressed: run last cascade-akka/*:publish for the full output.
[trace] Stack trace suppressed: run last cascade-common/*:publish for the full output.
[trace] Stack trace suppressed: run last cascade-http/*:publish for the full output.
[error] (cascade-json/*:publish) java.io.IOException: PUT operation to URL https://jcenter.bintray.com/com/paypal/cascade-json_2.11/0.1.5-SNAPSHOT/cascade-json_2.11-0.1.5-SNAPSHOT.pom failed with status code 405: Method Not Allowed
[error] (cascade-akka/*:publish) java.io.IOException: PUT operation to URL https://jcenter.bintray.com/com/paypal/cascade-akka_2.11/0.1.5-SNAPSHOT/cascade-akka_2.11-0.1.5-SNAPSHOT-tests.jar failed with status code 405: Method Not Allowed
[error] (cascade-common/*:publish) java.io.IOException: PUT operation to URL https://jcenter.bintray.com/com/paypal/cascade-common_2.11/0.1.5-SNAPSHOT/cascade-common_2.11-0.1.5-SNAPSHOT.pom failed with status code 405: Method Not Allowed
[error] (cascade-http/*:publish) java.io.IOException: PUT operation to URL https://jcenter.bintray.com/com/paypal/cascade-http_2.11/0.1.5-SNAPSHOT/cascade-http_2.11-0.1.5-SNAPSHOT.pom failed with status code 405: Method Not Allowed
[error] Total time: 158 s, completed Nov 19, 2014 12:18:50 AM
```

running `last cascade-json/*:publish` produces output that doesn't look very helpful:

``` bash
> last cascade-json/*:publish
java.io.IOException: PUT operation to URL https://jcenter.bintray.com/com/paypal/cascade-json_2.11/0.1.5-SNAPSHOT/cascade-json_2.11-0.1.5-SNAPSHOT.pom failed with status code 405: Method Not Allowed
    at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
    at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
    at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
    at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
    at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
    at sbt.ConvertResolver$ChecksumFriendlyURLResolver$class.put(ConvertResolver.scala:78)
    at sbt.ConvertResolver$PluginCapableResolver$1.put(ConvertResolver.scala:103)
    at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:287)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:286)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at sbt.IvyActions$.publish(IvyActions.scala:286)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply$mcV$sp(IvyActions.scala:113)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:113)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:113)
    at sbt.IvyActions$.withChecksums(IvyActions.scala:122)
    at sbt.IvyActions$.sbt$IvyActions$$withChecksums(IvyActions.scala:117)
    at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:113)
    at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:106)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:119)
    at sbt.IvySbt.withIvy(Ivy.scala:116)
    at sbt.IvySbt$Module.withModule(Ivy.scala:147)
    at sbt.IvyActions$.publish(IvyActions.scala:106)
    at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1215)
    at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1214)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

I am running this from [this branch](https://github.com/paypal/cascade/tree/feature/bintray), and have been able to consistently reproduce the issue.

**Comment by softprops** [comment]
Ill have to take a closer look but one thing stands out is the snapshot versions. I don't think bintray supports publishing varying package versions with the same snapshot version. I expect a different error message in this case though. It also looks like you are publishing directly to jcenter. I'm not sure you are supposed to do that. A typical workflow is to create a package under a repo you own, typically youraccount/maven, and have that repo "link" to jcenter it it can be automatically resolved by anyone with jcenter in their resolve chain.

**Comment by 2m** [comment]
Closing since the artifact was a snapshot and was being published straight to JCenter repo.
