### ISSUE TITLE
Settings logger used after project was loaded

### ISSUE THREAD

**Issue by JohnReedLOL** [sbt/sbt-bintray#85]
```
> publish
[info] Packaging /home/johnreed/sbtProjects/scala-trace-debug/target/scala-2.11/scala-trace-debug_2.11-0.1.3-sources.jar ...
[info] Done packaging.
[info] Packaging /home/johnreed/sbtProjects/scala-trace-debug/target/scala-2.11/scala-trace-debug_2.11-0.1.3-javadoc.jar ...
[info] Wrote /home/johnreed/sbtProjects/scala-trace-debug/target/scala-2.11/scala-trace-debug_2.11-0.1.3.pom
[info] :: delivering :: scala-trace-debug#scala-trace-debug_2.11;0.1.3 :: 0.1.3 :: release :: Mon Mar 28 21:18:38 EDT 2016
[info]  delivering ivy file to /home/johnreed/sbtProjects/scala-trace-debug/target/scala-2.11/ivy-0.1.3.xml
[info] Done packaging.
[info]  published scala-trace-debug_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/scala-trace-debug/scala-trace-debug_2.11/0.1.3/scala-trace-debug_2.11-0.1.3.pom
[info]  published scala-trace-debug_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/scala-trace-debug/scala-trace-debug_2.11/0.1.3/scala-trace-debug_2.11-0.1.3.jar
[info]  published scala-trace-debug_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/scala-trace-debug/scala-trace-debug_2.11/0.1.3/scala-trace-debug_2.11-0.1.3-sources.jar
[info]  published scala-trace-debug_2.11 to https://api.bintray.com/maven/johnreed2/maven/maven/scala-trace-debug/scala-trace-debug_2.11/0.1.3/scala-trace-debug_2.11-0.1.3-javadoc.jar
[trace] Stack trace suppressed: run last *:bintrayRelease for the full output.
[error] (*:bintrayRelease) Settings logger used after project was loaded.
[error] Total time: 24 s, completed Mar 28, 2016 9:19:02 PM
> last *:bintrayRelease
java.lang.RuntimeException: Settings logger used after project was loaded.
        at scala.sys.package$.error(package.scala:27)
        at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
        at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.LogManager$$anon$1.slog(LogManager.scala:110)
        at sbt.LogManager$$anon$1.log(LogManager.scala:115)
        at sbt.Logger$class.info(Logger.scala:118)
        at sbt.LogManager$$anon$1.info(LogManager.scala:108)
        at bintray.BintrayRepo.release(BintrayRepo.scala:73)
        at bintray.BintrayPlugin$$anonfun$bintrayPublishSettings$16.apply(BintrayPlugin.scala:117)
        at bintray.BintrayPlugin$$anonfun$bintrayPublishSettings$16.apply(BintrayPlugin.scala:114)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:bintrayRelease) Settings logger used after project was loaded.
> 

```

**Comment by oliverlockwood** [comment]
Still seeing this stacktrace, over a year since this issue was raised.  Which is a bit sad 😢 

To add a little more detail, it only occurs when running `sbt` in interactive mode.  In batch mode you don't see it (in my case, because I have `bintrayReleaseOnPublish` set to `false`, I get a warning log saying
>[warn] You must run bintrayRelease once all artifacts are staged.

It looks like the problem is that [this code](https://github.com/sbt/sbt-bintray/blob/0.3.0/src/main/scala/BintrayPlugin.scala#L146-L147) uses the settings logger.

The bug still exists in `master` [here](https://github.com/sbt/sbt-bintray/blob/master/src/main/scala/BintrayPlugin.scala#L142-L143).

**Comment by dwijnand** [comment]
This should be just a case of switching to `streams.value.log`. Do you fancy contributing to sbt-bintray?

**Comment by oliverlockwood** [comment]
Sure.  Will have a look at that now.

**Comment by oliverlockwood** [comment]
Note that this also affects `bintrayPackageVersions`:

```
project-name(master)> bintrayPackageVersions
[trace] Stack trace suppressed: run last \*:bintrayPackageVersions for the full output.
[error] (*:bintrayPackageVersions) Settings logger used after project was loaded.
[error] Total time: 0 s, completed 15-Jun-2017 07:58:45
```

Also note that you may need to run `clean` in the interactive console first to reproduce the issue.

**Comment by oliverlockwood** [comment]
PR #111 now raised to address this.

**Comment by oliverlockwood** [comment]
This should now be fixed and I guess will be made available in the next release.  @JohnReedLOL, if you'd like to test the fix before then by compiling `sbt-bintray` locally, you can do so as follows:
-  pull the latest code in `master`
-  tweak [line 4 of `build.sbt`](https://github.com/sbt/sbt-bintray/blob/master/build.sbt#L4) to give your local copy a different build identifier
-  run `sbt publishLocal` and `sbt publishM2`
-  update your dependent project to use your custom build of `sbt-bintray`.

**Comment by dwijnand** [comment]
As Oliver says: this has been solved (though yet unreleased) with https://github.com/sbt/sbt-bintray/pull/111.
