### ISSUE TITLE
Can't publish

### ISSUE THREAD

**Issue by 0xbaadf00d** [sbt/sbt-bintray#94]
Hi,

i have install your plugin on my SBT plugin project, but the command `sbt publish` continue to try to publish on SonaType. Is configuration steps are missing from your README ?

**Comment by PhilAndrew** [comment]
I was able to publish, 

1) set my ~/.bintray/.credentials correctly with API Key as password.

2) Add this project sbt-bintray as instructed to my sbt project.

3) in my build.sbt

```
bintrayPackage := "sbt-osgi-felix-p"

bintrayRepository := "sbt-osgi-felix-p"

bintrayOrganization := Some("philandrew") // The organization is not the same as the username I logged into bintray with

publishMavenStyle := true // true or false, it still published

licenses += ("MIT", url("http://opensource.org/licenses/MIT"))

bintrayReleaseOnPublish in ThisBuild := false // true or false, it still published

```

I can tell you that worked for me.

**Comment by ktoso** [comment]
I'm also somewhat stuck releasing and was not able to upgrade my other plugins to this one...

My build: 

```
sbtPlugin := true
publishTo := Some(Classpaths.sbtPluginReleases)
publishMavenStyle := false

// bintray config
bintrayOrganization := Some("ktosopl")
bintrayRepository := "sbt-plugins"
bintrayPackage := "sbt-multi-release-jar"
```

I have write access to the organisation and have created the specific package as well.. so this should work fine.

It fails in a very weird way with a 404 on publishing:

```
sbt:sbt-multi-release-jar> publish
[info] Packaging /Users/ktoso/code/sbt-multi-release-jar/target/scala-2.12/sbt-1.0/sbt-multi-release-jar-0.1.0.jar ...
[info] Done packaging.
[info] :: delivering :: com.lightbend.sbt#sbt-multi-release-jar;0.1.0 :: 0.1.0 :: release :: Tue Aug 29 20:54:57 JST 2017
[info] 	delivering ivy file to /Users/ktoso/code/sbt-multi-release-jar/target/scala-2.12/sbt-1.0/ivy-0.1.0.xml
[error] java.io.IOException: PUT operation to URL https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.sbt/sbt-multi-release-jar/scala_2.12/sbt_1.0/0.1.0/jars/sbt-multi-release-jar.jar failed with status code 404: Not Found
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
[error] 	at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:167)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:
```

I'm logged in and credential work...

```
sbt:sbt-multi-release-jar> bintrayEnsureCredentials
[success] Total time: 0 s, completed 29 Aug 2017, 20:56:42
sbt:sbt-multi-release-jar> bintrayWhoami
[info] ktosopl
```

Any idea what might be wrong here? The build I'm trying to fix is: https://github.com/sbt/sbt-multi-release-jar

**Comment by ktoso** [comment]
The moment I posted this I realised the mistake:
Note in my above code I'm using the old publishTo style - that's *bad*, and once I removed that it published just fine.

```
sbtPlugin := true
//publishTo := Some(Classpaths.sbtPluginReleases) // THIS IS BAD IN THE CURRENT PLUGIN VERSION
publishMavenStyle := false

// bintray config
bintrayOrganization := Some("ktosopl")
bintrayRepository := "sbt-plugins"
bintrayPackage := "sbt-multi-release-jar"

```

Leaving this here in case it might help someone with a similar migration issue.
Happy hakking!

**Comment by dwijnand** [comment]
Cheers Konrad. As a stopgap we should add that caveat to the readme.

**Comment by 2m** [comment]
Several different issues were discussed here with the original issue lacking additional information. Therefore closing this.
